EPOH/Assets/Scenes/Kyoungmin.unity
EPOH/Assets/Scenes/Kyoungmin.unity.meta
EPOH/ProjectSettings/ProjectSettings.asset

Test : Kyoungmin 씬 생성

---

EPOH/Assets/Scenes/Songein.unity
EPOH/Assets/Scenes/Songein.unity.meta

Scenes 폴더 내에 테스트용 개인 씬(Songein) 추가

Test: Songein 테스트 씬 추가

---

EPOH/Assets/Scenes/MinJu.unity
EPOH/Assets/Scenes/MinJu.unity.meta
EPOH/ProjectSettings/SceneTemplateSettings.json

Test: MinJu 씬 추가

---

EPOH/.idea/.idea.EPOH/.idea/.gitignore
EPOH/.idea/.idea.EPOH/.idea/indexLayout.xml
EPOH/.idea/.idea.EPOH/.idea/vcs.xml
EPOH/Assets/Kyoungmin.meta
EPOH/Assets/Kyoungmin/Animations.meta
EPOH/Assets/Kyoungmin/Animations/Dash.anim
EPOH/Assets/Kyoungmin/Animations/Dash.anim.meta
EPOH/Assets/Kyoungmin/Animations/Idle.anim
EPOH/Assets/Kyoungmin/Animations/Idle.anim.meta
EPOH/Assets/Kyoungmin/Animations/IdleTransition.anim
EPOH/Assets/Kyoungmin/Animations/IdleTransition.anim.meta
EPOH/Assets/Kyoungmin/Animations/Jump.anim
EPOH/Assets/Kyoungmin/Animations/Jump.anim.meta
EPOH/Assets/Kyoungmin/Animations/JumpFall.anim
EPOH/Assets/Kyoungmin/Animations/JumpFall.anim.meta
EPOH/Assets/Kyoungmin/Animations/JumpMid.anim
EPOH/Assets/Kyoungmin/Animations/JumpMid.anim.meta
EPOH/Assets/Kyoungmin/Animations/JumpRise.anim
EPOH/Assets/Kyoungmin/Animations/JumpRise.anim.meta
EPOH/Assets/Kyoungmin/Animations/PlayerAnimator.controller
EPOH/Assets/Kyoungmin/Animations/PlayerAnimator.controller.meta
EPOH/Assets/Kyoungmin/Animations/Run.anim
EPOH/Assets/Kyoungmin/Animations/Run.anim.meta
EPOH/Assets/Kyoungmin/Scripts.meta
EPOH/Assets/Kyoungmin/Scripts/PlayerController.cs
EPOH/Assets/Kyoungmin/Scripts/PlayerController.cs.meta
EPOH/Assets/Scenes/Kyoungmin.unity
EPOH/ProjectSettings/InputManager.asset
EPOH/ProjectSettings/TagManager.asset
EPOH/ProjectSettings/TimelineSettings.asset

- 플레이어 이동, 점프, 상호작용 구현
- 플레이어 대쉬 1차 구현

Feat : 플레이어 이동, 점프, 상호작용, 대쉬 1차

---

EPOH/Assets/Kyoungmin/Animations/PlayerAnimator.controller
EPOH/Assets/Kyoungmin/Scripts/PlayerController.cs
EPOH/Assets/Scenes/Kyoungmin.unity
EPOH/ProjectSettings/InputManager.asset
EPOH/ProjectSettings/TimelineSettings 2.asset

- 플레이어 대쉬 구현
- 변수명 통일, 주석 추가 등 코드 정리
- InputMangaer에 Dash, Interact 추가

Feat : 대쉬 2차 & Style : 코드 정리

---

EPOH/Assets/Kyoungmin/Animations/PlayerAnimator.controller
EPOH/Assets/Kyoungmin/Animations/TeleportStart.anim
EPOH/Assets/Kyoungmin/Animations/TeleportStart.anim.meta
EPOH/Assets/Kyoungmin/Prefabs.meta
EPOH/Assets/Kyoungmin/Prefabs/port.prefab
EPOH/Assets/Kyoungmin/Prefabs/port.prefab.meta
EPOH/Assets/Kyoungmin/Scripts/PlayerAttack.cs
EPOH/Assets/Kyoungmin/Scripts/PlayerAttack.cs.meta
EPOH/Assets/Kyoungmin/Scripts/PlayerController.cs
EPOH/Assets/Scenes/Kyoungmin.unity
EPOH/ProjectSettings/InputManager.asset

- 플레이어 2단 점프 기능
- 플레이어 순간이동
- 플레이어 콤보 공격(1차)

Feat : 플레이어 2단 점프, 순간이동, 콤보 공격(1차)

---

EPOH/Assets/Kyoungmin/Animations/PlayerAnimator.controller
EPOH/Assets/Kyoungmin/Scripts/AttackArea.cs
EPOH/Assets/Kyoungmin/Scripts/AttackArea.cs.meta
EPOH/Assets/Kyoungmin/Scripts/AttackBehaviour.cs
EPOH/Assets/Kyoungmin/Scripts/AttackBehaviour.cs.meta
EPOH/Assets/Kyoungmin/Scripts/Enemy.cs
EPOH/Assets/Kyoungmin/Scripts/Enemy.cs.meta
EPOH/Assets/Kyoungmin/Scripts/IdleBehaviour.cs
EPOH/Assets/Kyoungmin/Scripts/IdleBehaviour.cs.meta
EPOH/Assets/Kyoungmin/Scripts/PlayerAttack.cs
EPOH/Assets/Kyoungmin/Scripts/PlayerController.cs
EPOH/Assets/Kyoungmin/Scripts/TransitionOneBehaviour.cs
EPOH/Assets/Kyoungmin/Scripts/TransitionOneBehaviour.cs.meta
EPOH/Assets/Kyoungmin/Scripts/TransitionTwoBehaviour.cs
EPOH/Assets/Kyoungmin/Scripts/TransitionTwoBehaviour.cs.meta
EPOH/Assets/Scenes/Kyoungmin.unity
EPOH/Assets/Sprites/DeadRevolver/PixelPrototypePlayerSprites/Art/Animations/Idle.anim
EPOH/ProjectSettings/TagManager.asset

- 콤보 공격 기능을 위한 스크립트 추가
- 플레이어 중력 값 수정 1 -> 1.3

Feat : 플레이어 콤보 공격 기능

---

EPOH/.editorconfig
EPOH/Assets/Scenes/Corrider.unity
EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scenes/Start.unity
EPOH/Assets/Scripts/BossButton_Corrider/BossSelection.cs
EPOH/Assets/Scripts/BossButton_Corrider/EnterBossRoom.cs
EPOH/Assets/Scripts/GameManager.cs
EPOH/Assets/Scripts/Songein_PlayerController.cs
EPOH/ProjectSettings/EditorBuildSettings.asset

- chore: Build Setting에 BossRoomPartTime Scene 추가
- fix: 마우스 오버 시 Button Highlighted 되는 부분 수정
- feat: GameManager 싱글톤화
- feat: .editorconfig 파일 추가

Week3 GameManger 싱글톤화 및 버튼 Selected 관련 디테일 수정

---

EPOH/Assets/Kyoungmin/Scripts/AttackArea.cs

- AttackArea.cs 내 collider 할당 코드를 Awake()에서 실행하도록 변경하여 해결

Fix : Player NullReferenceException 에러 해결

---

EPOH/Assets/Kyoungmin/Scripts/IdleBehaviour.cs
EPOH/Assets/Minju/BossRunning.cs
EPOH/Assets/Minju/BossStomping.cs
EPOH/Assets/Scenes/BossRoom_MinJu.unity
EPOH/Assets/Scripts/BossButton_Corrider/EnterBossRoom.cs

[IdleBehaviour.cs 수정]
IdleBehaviour.cs 에서 FindObjectOfType<PlayerController>()로 찾은 객체가 null이 아닌지 확인하는 코드 추가
[보스 패턴 발구르기 플레이어 데미지 수정]
보스 패턴 '발구르기'에서 플레이어 가 충격파와 충돌하여 데미지를 입도록 수정함

Week 4 minju

---

EPOH/Assets/Scenes/Boss_Songein.unity
EPOH/Assets/Scenes/Boss_Songein.unity.meta
EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scripts/BossTrack.cs
EPOH/Assets/Scripts/BossTrack.cs.meta
EPOH/Assets/Scripts/CameraController.cs
EPOH/Assets/Scripts/CameraController.cs.meta

- 보스가 일정 주기로 캐릭터를 추적하는 기능 구현
- 카메라가 일정 범위 내에서 플레이어 캐릭터를 추적하는 기능 구현

Feat: 보스 이동 및 카메라 워킹 구현

---

EPOH/Assets/Scenes/Corrider.unity
EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scripts/BossButton_Corrider/EnterBossRoom.cs
EPOH/Assets/Scripts/GameManager.cs

Fix: Corrider 씬에서 선택한 BossRoom 이동 수정

---

EPOH/Assets/Scenes/Corrider.unity
EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scenes/MissionClear.unity
EPOH/Assets/Scripts/BossButton_Corrider/MissionDecisionCorrider.cs
EPOH/Assets/Scripts/Player/Attack/IdleBehaviour.cs
EPOH/Assets/Scripts/Player/PlayerBossFight.cs

-임무완료 씬에 나오는 팝업창 생성함
-MainRoom의 팝업창 버튼들을 키보드로도 선택가능하게 수정

Week 5 minju

---

EPOH/Assets/Kyoungmin/Scripts/BossHealth.cs
EPOH/Assets/Scenes/BossRoom_MinJu.unity
EPOH/Assets/Scripts/BossButton_Corrider/MissionDecisionCorrider.cs
EPOH/Assets/Scripts/BossDog/Running/BossRunning.cs
EPOH/Assets/Scripts/BossDog/Stomping/BossStomping.cs

BossRunning.cs
BossStomping.cs 수정

Refactor: BossRunning, BossStomping 스크립트 수정

---

EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scripts/BossButton_Corrider/MissionDecisionCorrider.cs
EPOH/Assets/Scripts/BossDog/Running/BossRunning.cs
EPOH/Assets/Scripts/BossDog/Stomping/BossStomping.cs
EPOH/Assets/Scripts/Interact/ActivatePortalInteract.cs

위젯의 보스 미션 버튼들 중 하나를 선택한 후 뜨는 임무결정 팝업에서 no 버튼을 누른 후 다시 다른 보스 미션 버튼을 누르고 임무결정 팝업이 떴을 때 yes 버튼이 디폴트로 선택되어 있도록 수정

Fix: 위젯 임무결정 팝업의 No 버튼 오류 수정

---

EPOH/Assets/Scenes/BossRoomDog.unity
EPOH/Assets/Scripts/BossDog/BossDog.cs

- 보스 돌진(Running) 구현
- 보스 발구르기(Stomping) 구현

Feat: 보스 Running, Stomping 패턴 개발

---

EPOH/Assets/Scenes/Tutorial MainRoom.unity
EPOH/Assets/Scripts/Interact/TutorialWidgetInteraction.cs
EPOH/Assets/Scripts/Interact/TutorialWidgetInteraction.cs.meta
EPOH/Assets/Scripts/TutorialEvent/Event1Script.cs
EPOH/Assets/Scripts/TutorialEvent/Event2Script.cs
EPOH/Assets/Scripts/TutorialEvent/Event3Script.cs
EPOH/Assets/Scripts/TutorialEvent/Event3Script.cs.meta
EPOH/Assets/Scripts/TutorialEvent/Event4Script.cs
EPOH/Assets/Scripts/TutorialEvent/Event4Script.cs.meta
EPOH/Assets/Scripts/TutorialEvent/ScrollViewControl.cs
EPOH/Assets/Scripts/TutorialEvent/ScrollViewControl.cs.meta

[Event 3 생성]
-위젯과 상호작용할 경우 Dog에 대한 의뢰서가 나옴
-시작할 때는 ACCEPT 버튼이 없다가, 유저가 space를 클릭하거나 의뢰서를 다 읽으면(키보드 ↓로 스크롤 등) 주인공 대사가 나오고 ACCEPT 버튼 생김
[Event 4 생성]
-ACCEPT 버튼 누를시 안내음 이벤트 진행
[주인공 대화창 이름을 "주인공"-> "나"로 수정]

Week 7 minju

---

EPOH/Assets/Kyoungmin/Scripts/BossHealth.cs
EPOH/Assets/Scripts/BossDog/BossDog.cs
EPOH/Assets/Scripts/BossDog/BossDogScene.cs

- Design: 보스룸 그래픽 교체
- Feat: 카메라 이동 및 대화창 구현
- Feat: Event 5 구현
- Feat: Event 6 1차 구현

Feat : 이벤트 및 보스전 구현

---

EPOH/Assets/Scenes/Tutorial MainRoom.unity
EPOH/Assets/Scripts/TutorialEvent/Event3Script.cs
EPOH/Assets/Scripts/TutorialEvent/Event3Talk.cs
EPOH/Assets/Scripts/TutorialEvent/Event3Talk.cs.meta

Event 3에서 스크롤 맨 끝까지 내리거나 space를 눌러서 맨 끝 위치로 이동하면 대사창 나옴

Fix: Event 3에서 스크롤 맨 끝에서 대사창 나옴

---

EPOH/Assets/Kyoungmin/Prefabs/Player.prefab
EPOH/Assets/Scenes/Start.unity
EPOH/Assets/Scenes/Tutorial MainRoom.unity
EPOH/Assets/Scripts/Player/Movement/PlayerController.cs

-플레이어 효과음 볼륨 변경(1->0.5)
-달리기 효과음 시간텀 조정

Fix: 효과음 볼륨 조정 및 달리기 효과음 시간 텀 조정

---

EPOH/Assets/Kyoungmin/Prefabs/Player.prefab

Fix: 플레이어 효과음 볼륨 수정

---

EPOH/Assets/Scripts/Player/Movement/PlayerController.cs

플레이어 발소리 착지, 뛰기 효과음 볼륨 0.5로 조절

Fix: 플레이어 발소리 착지, 뛰기 효과음 볼륨 조절

---

EPOH/Assets/Scripts/BossDog/BossDog.cs
EPOH/Assets/Scripts/BossDog/BossDogScene.cs

[보스 페이즈 변환시 패턴 강화]
달리기: 3회 연속 공격으로 변화
하울링: 범위 1.5배가량 증가
발구르기: 충격파가 양쪽으로 발생
물기: 2회 연속 공격으로 변화

Week 7 minju2

---

EPOH/Assets/Kyoungmin/Prefabs/Player.prefab
EPOH/Assets/Scenes/BossRoomDog.unity
EPOH/Assets/Scripts/Hacking.cs
EPOH/Assets/Scripts/Player/Attack/PlayerAttack.cs

combo1 공격 수치 = 20 -> 30
combo2 공격 수치 = 40 -> 50
hacking 수치 = 10 -> 5

Feat: boss_hp, hacking_point 수치 조정

---

EPOH/Assets/Scenes/BossRoomDog.unity
EPOH/Assets/Scenes/Corrider.unity
EPOH/Assets/Scripts/BossDog/BossDogScene.cs
EPOH/Assets/Scripts/Player/Movement/PlayerController.cs
EPOH/Assets/TalkEventArea.cs

- Corrider 씬에 투명 벽 추가
- BossRoomScene에 사용하지 않는 오브젝트 삭제
- PlayerController.cs에서 대화중 대쉬가 가능했던 버그 수정

Fix: 이벤트 중에 플레이어 동작 가능 버그 수정

---

EPOH/Assets/Scenes/Corrider.unity
EPOH/Assets/Scenes/Tutorial MainRoom2.unity
EPOH/Assets/Scenes/Tutorial MainRoom2.unity.meta
EPOH/ProjectSettings/EditorBuildSettings.asset

-Corrider 씬에서 left portal로 이동하면 Tutorial MainRoom2로 이동하도록 수정 
-Tutorial MainRoom2에서 portal 이용시 Corrider로 이동

Fix: Corrider 씬의 left portal 이동 수정

---

EPOH/Assets/Scenes/Corrider2.unity
EPOH/Assets/Scripts/BossDog/BossDog.cs
EPOH/Assets/Scripts/BossDog/BossDogScene.cs

- 보스전 페이즈 2에서 튜토리얼 창 닫히고 보스 공격 시작
- Scenes In Build에 'MainRoom' 추가

Fix: 보스전 페이즈 2에서 튜토리얼 창 닫히고 보스 공격 시작

---

EPOH/Assets/Scenes/Tutorial MainRoom.unity
EPOH/ProjectSettings/EditorBuildSettings.asset

Design: 튜토리얼 메인룸 포탈 위치 조정

---

EPOH/Assets/Scripts/Player/Movement/PlayerController.cs

보스룸에서 플레이어 1단 점프 후 착지 기계음 오류 수정

Fix: 플레이어 1단 점프 후 착지 효과음 수정

---

EPOH/Assets/Scenes/MainRoom.unity
EPOH/Assets/Scenes/MainRoom_Before.unity
EPOH/Assets/Scenes/Tutorial MainRoom2.unity

Tutorial MainRoom2, MainRoom의 포탈 위치를 Tutorial MainRoom의 포탈 위치와 같게 조정

Fix: Tutorial MainRoom2, MainRoom 포탈 위치 조정

---

EPOH/Assets/Prefabs/Player.prefab
EPOH/Assets/Scenes/PlayerAni.unity
EPOH/Assets/Scripts/Player/Movement/PlayerController.cs
EPOH/Assets/Sprites/Player/Attack/Attack One.anim
EPOH/Assets/Sprites/Player/Attack/Attack Two.anim
EPOH/Assets/Sprites/Player/Idle/Idle.anim
EPOH/Assets/Sprites/Player/Mark/InstallMark.anim
EPOH/Assets/Sprites/Player/Run/Run.anim

- 떨어지는 중이 아니더라도 땅을 감지하면 애니메이션이 중지되도록 변경.
- 두 번째 점프가 첫 번째 점프보다 낮게 변경
- 애니메이션 프레임 조절

[FIX]: 플레이어 조작 및 애니메이션 수정

---

EPOH/Assets/Prefabs/3_Criminal/0.Password/PasswordB.prefab
EPOH/Assets/Prefabs/3_Criminal/0.Password/PasswordY.prefab
EPOH/Assets/Scripts/Boss/3_Criminal/0.Password/newPasswordSkill.cs

Feat: Password
